// import { satoshi } from "@/utils/fonts";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "First Startup",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`  antialiased`}>
        <Toaster position="top-right" />
        {children}
      </body>
    </html>
  );
}
