// import { satoshi } from "@/utils/fonts";
// import Toaster from "@/components/Toaster";
import "./globals.css";
import ClientBody from "./ClientBody";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "First Startup",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ClientBody>
          {children}
          <Toaster position="top-right" />
        </ClientBody>
      </body>
    </html>
  );
}
